### ISSUE TITLE
Add templates

### ISSUE THREAD

**Issue by NeonGamerBot-QK** [endo9000/Awesome-Ollama#11]
Adding a CONTRIBUTING.md file and an issue template would help people on how to add there work.

**Comment by endo9000** [comment]
good point. thanks!
pretty new to all this github game. 
going to do some more work around the week. 🙌

**Comment by NeonGamerBot-QK** [comment]
Nice! i can write a PR with a basic version of it.

**Comment by endo9000** [comment]
would gladly take the contribution. 🙌

**Comment by NeonGamerBot-QK** [comment]
#13 pr

**Comment by endo9000** [comment]
thanks just rebased it! looking good to me. 👍

**Comment by NeonGamerBot-QK** [comment]
Nice
![image](https://github.com/endo9000/Awesome-Ollama/assets/58448036/7eff3518-b718-436f-b72c-22a122db6d35)
